name: 'Setup Snowflake'
description: 'Download, install and configure SnowSQL'
inputs:
  SNOWSQL_ACCOUNT:
    description: 'SnowSQL Account'
    required: true
  SNOWSQL_USER:
    description: 'SnowSQL User'
    required: true
  SNOWSQL_PWD:
    description: 'SnowSQL Password'
    required: true
  SNOWSQL_ROLE:
    description: 'SnowSQL Role'
    required: true
  SNOWSQL_WAREHOUSE:
    description: 'SnowSQL Warehouse'
    required: true
  SNOWSQL_DATABASE:
    description: 'SnowSQL Database'
    required: true
  SNOWFLAKE_SCHEMA:
    description: 'Snowflake Schema'
    required: true
  ENV_NAME:
    description: 'Environment Name'
    required: true
runs:
  using: 'composite'
  steps:
  - name: Download SnowSQL
    shell: bash
    run: curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.9-linux_x86_64.bash

  - name: Install SnowSQL
    shell: bash
    run: SNOWSQL_DEST=~/bin SNOWSQL_LOGIN_SHELL=~/.profile bash snowsql-1.2.9-linux_x86_64.bash

  - name: Configure snowcli
    shell: bash
    run: |
      mkdir -p ~/.snowsql
      echo "accountname = ${{ inputs.SNOWSQL_ACCOUNT }}" >> ~/.snowsql/config
      echo "username = ${{ inputs.SNOWSQL_USER }}" >> ~/.snowsql/config
      echo "password = ${{ inputs.SNOWSQL_PWD }}" >> ~/.snowsql/config
      echo "rolename = ${{ inputs.SNOWSQL_ROLE }}" >> ~/.snowsql/config
      echo "warehousename = ${{ inputs.SNOWSQL_WAREHOUSE }}" >> ~/.snowsql/config
      echo "dbname = ${{ inputs.SNOWSQL_DATABASE }}" >> ~/.snowsql/config
      echo "schemaname = ${{ inputs.SNOWFLAKE_SCHEMA }}" >> ~/.snowsql/config
